### ISSUE TITLE
ToDo: Frontend

### ISSUE THREAD

**Issue by jd-apprentice** [jd-apprentice/waifuland-fe#10]
- [x] Migrate from MUI to Chakra UI
- [x] Refactor HTML-CSS
- [x] Build login page
- [x] Error validations
- [ ] Finish styles
- [ ] New design
- [x] Responsive design
- [x] Add `images` page

**Comment by jd-apprentice** [comment]
Production build is now being hosted on my server -> [here](https://app.jonathan.com.ar/)
Development is hosted in -> [vercel](https://waifuland-fe.vercel.app/)

Either environment has his own db (they are similar in the amount of images)

**Comment by jd-apprentice** [comment]
- [x] Add `images` pages #16

**Comment by jd-apprentice** [comment]
- [x] Build login page #28

**Comment by jd-apprentice** [comment]
@chechdebug Could you help me with the last 2 tasks <3?

**Comment by chechdebug** [comment]
Lemme think about it, probably if I got some ⌛
